### PR TITLE
Add ability to change behavior of ForceLog

### PR DESCRIPTION
**Pull request by dssysolyatin**
In my project I don't need to write azure error logs to syslog. I suggest to define ForceLog as variable in order to be ability to change ForceLog behavior.

### CODE REVIEW

**Comment by dssysolyatin** [comment]
Is anyone support this repository ?

**Comment by dssysolyatin** [comment]
Hi @JohnRusk !
Yes, PR #19 is comfortable for me. But would it be better if create `ForceLogger` interface and setter `SetForceLogger` ?
```
var forceLogger  ForceLogger

type ForceLogger interface{
     Log(level LogLevel, msg string)
}

func SetForceLogger(l ForceLogger) {
    forceLogger = l
}

func forceLog(level LogLevel, msg string){
      if forceLogger != nil {
           forceLogger.Log(level, msg)
      }
}
``` 

Then `LogSanitizer` interface isn't needed, because you can wrap ForceLogger. How do you think ?

**Comment by JohnRusk** [comment]
I'm not sure. I kind of like it, but I know that the original plan, when the package was first written, was for the forced logging to be on by default.  While that's certainly possible with your suggestion, your suggestion feels more aligned to something which would be off by default.  So, instead of making that change now, what I'll do instead is mention this discussion in the review comments on the new PR. The reviewers are more involved with the original code than I am. If they say we should change to what you've suggested, we can update the new PR.  If they're not so keen, we'll leave the new PR as-is.

**Comment by dssysolyatin** [comment]
@JohnRusk 
It would be great ! Thanks !

**Comment by JohnRusk** [comment]
@dssysolyatin It's been decided not to introduce ForceLogger.  But thanks for the suggestion and for pointing out the ability to turn off forced logging, which has now been merged to master (in the form of a Boolean setting in #19).

**Pull request closed without merging**
