### PR TITLE
Transitioned go-pipeline to proxyMiddleman

### PR DESCRIPTION
**Pull request by adreed-msft**
azure-pipeline-go now takes advantage of go-ieproxy. This is related to the other go-ieproxy request on azure-storage-azcopy

### CODE REVIEW

**Comment by adreed-msft** [comment]
@JohnRusk @zezha-msft This is a part of proxy detection for AzCopy, please review this in tandem with that PR.

**Comment by adreed-msft** [comment]
@JohnRusk Included it in go.mod

**Comment by zezha-msft** [comment]
Butter-fingered and forgot to squash. Sorry.

**Comment by chrislusf** [comment]
does not work with freebsd

**Comment by Virepri** [comment]
Oh? What errors are you getting?

**Comment by adreed-msft** [comment]
Oh? What errors are you getting?

**Comment by chrislusf** [comment]
# github.com/mattn/go-ieproxy
./GetProxyFunc.go:10:9: undefined: proxyMiddleman

**Comment by adreed-msft** [comment]
Ah. Yeah, that would make sense. I'll make a PR to go-ieproxy to add a whole bunch of OSes to the fallback proxyMiddleman.

**Comment by chrislusf** [comment]
Thanks! Add "!window" should work.

Or only call go-ieproxy in windows.

**Comment by adreed-msft** [comment]
@chrislusf latter wouldn't work, the code paths would still like to compile. Former may work on the preprocessor tags.

**Comment by chrislusf** [comment]
I mean a simple preprocessor tag can avoid calling go-ieproxy, which is only for windows.

**Comment by zezha-msft** [comment]
@adreed-msft we can address this in a patch.

**Pull request merged**
